# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "zabbix" do |zabbix|
    zabbix.vm.box = "zabbix"
    zabbix.vm.hostname = 'zabbix'
    zabbix.vm.box_url = "sbeliakou-vagrant-centos-7.3-x86_64-minimal.box"
#    zabbix.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
    zabbix.vm.network :private_network, ip: "192.168.56.10" 
    
    zabbix.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.name = "zabbix"
    end
zabbix.vm.provision "shell", path: "scripts/script.sh"
end
  config.vm.define "zabbix2" do |zabbix2|
    zabbix2.vm.box = "zabbix2"
    zabbix2.vm.hostname = 'zabbix2'
    zabbix2.vm.box_url = "sbeliakou-vagrant-centos-7.3-x86_64-minimal.box"
#    zabbix.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
    zabbix2.vm.network :private_network, ip: "192.168.56.11"   
    
    zabbix2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "zabbix2"
    end
zabbix2.vm.provision "shell", path: "scripts/script2.sh"
end
end
