# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

 config.vm.define "zabbix" do |zb|
    zb.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
    zb.vm.network "private_network", ip: "111.111.11.11"
    zb.vm.hostname = "zabbix"
    zb.vm.provider "virtualbox" do |v|
	v.memory = "2048"
	v.name = "zabbix"
    end

    zb.vm.synced_folder ".", "/home/vagrant/vb-share", create: true,
      owner: "vagrant", group: "vagrant", type: "virtualbox"

    zb.vm.provision "shell", inline: <<-SHELL
	chmod +x /home/vagrant/vb-share/scripts/server.sh
	/home/vagrant/vb-share/scripts/server.sh
    SHELL
  end

  config.vm.define "agent" do |ag|
    ag.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
    ag.vm.network "private_network", ip: "111.111.11.12"
    ag.vm.hostname = "agent"
    ag.vm.provider "virtualbox" do |v|
	v.memory = "2048"
	v.name = "agent"
    end

    ag.vm.synced_folder ".", "/home/vagrant/vb-share", create: true,
      owner: "vagrant", group: "vagrant", type: "virtualbox"

    ag.vm.provision "shell", inline: <<-SHELL
	chmod +x /home/vagrant/vb-share/scripts/agent.sh
	/home/vagrant/vb-share/scripts/agent.sh
    SHELL
  end
end
