Vagrant.configure("2") do |config|
  config.vm.define "zabbix" do |zabbix|
    zabbix.vm.box = "zabbix"
    zabbix.vm.hostname = 'zabbix'
    zabbix.vm.box_url = "sbeliakou-vagrant-centos-7.3-x86_64-minimal.box"
    zabbix.vm.network :forwarded_port, guest: 80, host: 8080
    zabbix.vm.network :private_network, ip: "192.168.56.10"
    zabbix.vm.synced_folder "share/", "/share"
    zabbix.vm.provider :virtualbox do |v|
      v.memory = "4096"
      v.name = "zabbixVM"
    end
    zabbix.vm.provision "shell", inline: <<-SHELL
    sudo su
    chmod +x /share/scripts/server.sh
    /share/scripts/server.sh
    SHELL
  end

  config.vm.define "agent" do |agent|
    agent.vm.box = "agent"
    agent.vm.hostname = 'agent'
    agent.vm.box_url = "sbeliakou-vagrant-centos-7.3-x86_64-minimal.box"
    agent.vm.network :private_network, ip: "192.168.56.11"
    agent.vm.synced_folder "share/", "/share"
    agent.vm.provider :virtualbox do |v|
      v.memory = "2048"
      v.name = "agent"
    end
    agent.vm.provision "shell", inline: <<-SHELL
    sudo su
    chmod +x /share/scripts/agent.sh
    /share/scripts/agent.sh
    SHELL
  end

end

