# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "zabbix_server" do |zabbix|
    zabbix.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
    zabbix.vm.hostname = "zabbix-server"
    server.vm.network "forwarded_port", guest: 80, host: 8080
    zabbix.vm.network "private_network", ip: "192.168.100.101"
    zabbix.vm.network "public_network", bridge: "enp8s0"
    zabbix.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.name = "zabbix_server"
    end
    zabbix.vm.post_up_message = "zabbix vm is loaded"
    zabbix.vm.provision "file", source: "./zabbix.conf.php", destination: "zabbix.conf.php"
    zabbix.vm.provision "file", source: "./pyScript.py", destination: "pyScript.py"
    zabbix.vm.provision "shell", path: "scripts/zabbix_server_script.sh"
    zabbix.vm.provision "shell", path: "scripts/zabbix_agent_script.sh"
 end
  config.vm.define "zabbix_agent" do |zabbix|
    zabbix.vm.box = "sbeliakou/centos-7.3-x86_64-minimal"
    zabbix.vm.hostname = "zabbix-agent"
    zabbix.vm.network "forwarded_port", guest: 8080, host: 8090
    zabbix.vm.network "private_network", ip: "192.168.100.102"
    zabbix.vm.network "public_network", bridge: "enp8s0"
    zabbix.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.name = "zabbix_agent"
    end
    zabbix.vm.post_up_message = "zabbix vm is loaded"
    zabbix.vm.provision "shell", path: "scripts/zabbix_agent_script.sh"
    zabbix.vm.provision "shell", path: "scripts/tomcat_install.sh"
    zabbix.vm.provision "shell", path: "scripts/zabbix_ext_agent.sh"
 end
end
