# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "zabbix_server" do |zabbix|
    zabbix.vm.box = "Centos-7.3"
    zabbix.vm.hostname = "zabbix"
    zabbix.vm.network :private_network, ip: "10.1.1.1"
    zabbix.vm.network "forwarded_port", guest: 80, host: 8080
    zabbix.vm.provider 'virtualvm' do |v|
        v.memory = "1000"
    end
    zabbix.vm.provision "shell", path: "provision/prov-zabbix.sh"
    zabbix.vm.provision "shell", path: "provision/prov-agent.sh"
  end

  config.vm.define("tomcat") do |tomcat|
        tomcat.vm.box = "Centos-7.3"
        tomcat.vm.hostname = "tomcat"
        tomcat.vm.network :private_network, ip: "10.1.1.2"
        tomcat.vm.provider 'virtualvm' do |v|
            v.memory = "500"
        end
    tomcat.vm.provision "shell", path: "provision/prov-tomcat.sh"
    tomcat.vm.provision "shell", path: "provision/prov-agent.sh"
  end
end

